%
% ts_plot = plot_expbur_time(exposed_or_not)
% ts_plot = plot_expbur_time(exposed_or_not,conc_plot)
%
% Plots an exposure-burial 'time series' that is used to drive the model.
%
% Requires the output generated by two_stage_logical.m, fit_core_expo.m, or
% fit_core_bur.m.
%
% A new figure is created, unless conc_plot (created using
% plot_core_concs.m or plot_2isotope_concs.m) is included, in which case a 
% subplot is created.
%
% The final part of the figure is a plot of exposure/burial periods,
% which should be generated using plot_ExpBur.m.
%
% Outputs are handles for the figure, time-series subplot, and tick marks 
% and labels for time (x) axis.
%
%
%%

function ts_plot = plot_expbur_time(exposed_or_not,conc_plot)

  % Check inputs
  if (nargin > 2)
      error('plot_expbur_time has too many inputs!');
  end
  
  if (nargin < 2)
      fig = figure;
      ts_a = subplot(2,1,1); EB_a = subplot(2,1,2);
      set(ts_a,'pos',[0.14 0.26 0.78 0.65]);
      set(EB_a,'pos',[0.14 0.18 0.78 0.06]);
      fontsize = 11;
  else
      ts_a = conc_plot(3);
      fontsize = 10;
  end
  
  % Check time data
  if max(exposed_or_not.reduced_time) > 1000000
      time = exposed_or_not.reduced_time / 1000000;
  elseif max(exposed_or_not.reduced_time) > 1000
      time = exposed_or_not.reduced_time / 1000;
  else
      time = exposed_or_not.reduced_time;
  end
  

  % Plot data
  axes(ts_a);
  stairs(time,exposed_or_not.reduced_values,'-','Color','k','Linewidth',1.5);
  ts_a.XLim = [min(time) max(time)];
  time_tick = ts_a.XTick;
  time_ticklab = ts_a.XTickLabel';
  ts_a.XTick = [];
  ts_a.YLim = [-0.5 1.5];
  ts_a.YTick = [0 1];
  ts_a.YTickLabel = [{'Buried','Exposed'}];
  ts_a.GridLineStyle = 'none';
  grid on;
  box on;
  
  set(ts_a,'FontSize',fontsize);
  
  
  % Export handles
  if (nargin < 2)
      ts_plot.fig = fig;
      ts_plot.EB_a = EB_a;
  end
  ts_plot.ts_a = ts_a;
  ts_plot.time_tick = time_tick;
  ts_plot.time_ticklab = time_ticklab;
  
  
end
