%
% ts_plot = plot_time_series(exposed_or_not)
% ts_plot = plot_time_series(exposed_or_not,conc_plot)
%
% Plots the time-series data and threshold used to drive the model.
%
% Requires the output generated by time_series_logical.m or
% ice_surface_logical.m
%
% A new figure is created, unless conc_plot (created using
% plot_core_concs.m or plot_2isotope_concs.m) is included, in which case a 
% subplot is created.
%
% The final part of the figure is a plot of exposure/burial periods,
% which should be generated using plot_ExpBur.m.
%
% Outputs are handles for the figure, time-series subplot, and tick marks 
% and labels for time (x) axis.
%
%
%%

function ts_plot = plot_time_series(exposed_or_not,conc_plot)

  % Check inputs
  if (nargin > 2)
      error('plot_time_series has too many inputs!');
  end
  
  if (nargin < 2)
      fig = figure;
      ts_a = subplot(2,1,1); EB_a = subplot(2,1,2);
      set(ts_a,'pos',[0.14 0.26 0.78 0.65]);
      set(EB_a,'pos',[0.14 0.18 0.78 0.06]);
      driver_lab = (strcat(num2str(exposed_or_not.name),{' ('},num2str(exposed_or_not.unit),')'));
      fontsize = 11;
  else
      ts_a = conc_plot(3);
      driver_lab = (strcat(num2str(exposed_or_not.short_name)));
      fontsize = 10;
  end
  
  % Check time data
  if max(exposed_or_not.time) > 1000000
      time = exposed_or_not.time / 1000000;
  elseif max(exposed_or_not.time) > 1000
      time = exposed_or_not.time / 1000;
  else
      time = exposed_or_not.time;
  end
  

  % Plot data
  axes(ts_a);
  
  hold on;
  if isempty(findobj('tag','time_series'))
      plot(time,exposed_or_not.values,'-','Color',[.5 .5 .5],'tag','time_series');
      set(findobj('tag','time_series'),'LineWidth',1);
  else
      set(findobj('tag','time_series'),'xdata',time,'ydata',exposed_or_not.values);
  end
  
  if isempty(findobj('tag','theshold'))
      plot([min(time) max(time)],[exposed_or_not.threshold exposed_or_not.threshold],':k','tag','theshold');
      set(findobj('tag','theshold'),'LineWidth',2);
  else
      set(findobj('tag','theshold'),'xdata',[min(time) max(time)],'ydata',[exposed_or_not.threshold exposed_or_not.threshold]);
  end
  hold off;
  
  ts_a.XLim = [min(time) max(time)];
  time_tick = ts_a.XTick;
  time_ticklab = ts_a.XTickLabel';
  %ts_a.XTick = [];
  %grid on;
  box on;
  ylabel(driver_lab);
  
  set(ts_a,'FontSize',fontsize);
  
  
  % Export handles
  if (nargin < 2)
      ts_plot.fig = fig;
      ts_plot.EB_a = EB_a;
  end
  ts_plot.ts_a = ts_a;
  ts_plot.time_tick = time_tick;
  ts_plot.time_ticklab = time_ticklab;
  
  
end
